steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/optimal-sun-208612/bxbet-api:$BUILD_ID', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/optimal-sun-208612/bxbet-api:$BUILD_ID']
- name: gcr.io/cloud-builders/kubectl
  args: ['set', 'image', 'deployment/bxbetapi', 'bxbetapi=gcr.io/optimal-sun-208612/bxbet-api:$BUILD_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bxbet-back	'
